services:
  search_db_vector:
    build: .
    volumes:
      - ./src:/app/src
      - ./app.py:/app/app.py
    ports:
        - "5001:5001"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST
    networks:
      - search_ai_net
networks:
  search_ai_net:
    external: true